spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
    admin:
      auto-create: true

  data:
    redis:
      host: localhost
      port: 6379

aws:
  region: ${AWS_REGION:ap-south-1}
  sns:
    topic-arn: ${AWS_SNS_TOPIC_ARN}

resilience4j:
  circuitbreaker:
    instances:
      snsService:
        failure-rate-threshold: 50
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3